### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by senj** [AleRoe/CecSharp#2]
Hello, 

if I want to use this for a real device, I need vendor ID which I may find on my device's settings, and a physical address, is this the MAC address ?

**Comment by AleRoe** [comment]
Hi @senj,
sorry for the delayed response.
The VendorID is a unique integer identifying the vendor of the device. The ID is supplied by the vendor itself. Some applications may use this to identify the capabilities supported by the device. Unfortunately, I could not find any public documentation on available vendor IDs. You can just supply any arbitrary number and it will work anyway. 
May I ask whart kind of device you are trying to control?
I'd be interested in your use case.

Cheers and kind regards
Alexander

**Comment by senj** [comment]
Hi Alexander,
the vendor ID is in my TV's settings. Now I need physical address?

I have a web application running on a raspberry pi. Now I want to power on/off my display (Xiaomi TV 32 zoll) from within the web application's code.

I managed to send some CEC commands from the bash, but I want to be able to send them from within the application based on user speech input.

**Comment by rubenfpinto** [comment]
Hi guys,

I have a question, i need to implement a hdmi-cec protocol in my windows .net app to on/off Tv's. 
Can you help me to understand what i need to do that? Or have some documentation?

When i create a new device (the arguments) it's need to consider a Tv or the windows pc what i use?

Thanks for the help
